#!/bin/sh
mkdir -p /lib/modules/$(uname -r)/kernel/drivers/nvidia
if [ -d ${SYNOPKG_PKGDEST}/lib/modules/drivers/nvidia ]; then
    cp ${SYNOPKG_PKGDEST}/lib/modules/drivers/nvidia/*.ko /lib/modules/$(uname -r)/kernel/drivers/nvidia/ 2>/dev/null || true
fi
if [ -f ${SYNOPKG_PKGDEST}/etc/modprobe.d/nvidia.conf ]; then
    cp ${SYNOPKG_PKGDEST}/etc/modprobe.d/nvidia.conf /etc/modprobe.d/
fi
depmod -a || true
exit 0
